version: '3'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
  moleculer:
    build: .
    environment:
      - TRANSPORTER=nats://nats:4222
    depends_on:
      - nats
    ports:
      - "3000:3000"
